import type { MediaAsset } from "@/components/projects/MediaCard";
import type { FolderNode } from "@/components/projects/FolderTree";

export interface DemoProject {
  id: string;
  name: string;
}

export function buildInternalDemoAssetHref(projectId: string, assetId: string) {
  return `/projects/${encodeURIComponent(projectId)}?demo=1&asset=${encodeURIComponent(assetId)}&view=review`;
}

export const demoProjects: DemoProject[] = [
  { id: "ica", name: "ICA" },
  { id: "schneider-epc", name: "Schneider + EPC" },
  { id: "bp", name: "bp" },
  { id: "acs", name: "Astro Cleaning Services" },
];

export const demoFolders: FolderNode[] = [
  {
    id: "ica",
    project_id: "ica",
    kind: "project",
    name: "ICA",
    children: [
      {
        id: "ica-executive-interviews",
        project_id: "ica",
        kind: "folder",
        name: "Executive Interviews",
        children: [],
      },
      {
        id: "ica-roadshow-master",
        project_id: "ica",
        kind: "folder",
        name: "Roadshow Master",
        children: [],
      },
    ],
  },
  {
    id: "schneider-epc",
    project_id: "schneider-epc",
    kind: "project",
    name: "Schneider + EPC",
    children: [
      {
        id: "schneider-roadshow",
        project_id: "schneider-epc",
        kind: "folder",
        name: "Nashville Roadshow",
        children: [],
      },
      {
        id: "schneider-podcast",
        project_id: "schneider-epc",
        kind: "folder",
        name: "McLaren Podcast",
        children: [],
      },
    ],
  },
  { id: "bp", project_id: "bp", kind: "project", name: "bp", children: [] },
  { id: "acs", project_id: "acs", kind: "project", name: "Astro Cleaning Services", children: [] },
];

export const demoAssets: MediaAsset[] = [
  {
    id: "denie-mcdonald-v4",
    project_id: "ica",
    folder_id: "ica-executive-interviews",
    title: "Denie McDonald_v4",
    thumbnail_url: "/demo/ceraweek-speaker.jpg",
    file_type: "video",
    duration_seconds: 71,
    status: "in_review",
    version_count: 4,
    reviewer_count: 2,
    reviewer_done: 1,
    comment_count: 6,
    created_at: "2026-07-14T21:53:00.000Z",
    href: buildInternalDemoAssetHref("ica", "denie-mcdonald-v4"),
  },
  {
    id: "charles-drummond-v5",
    project_id: "ica",
    folder_id: "ica-executive-interviews",
    title: "Charles Drummond_v5",
    thumbnail_url: "/demo/crew-field-shoot.jpg",
    file_type: "video",
    duration_seconds: 70,
    status: "needs_changes",
    version_count: 5,
    reviewer_count: 2,
    reviewer_done: 1,
    comment_count: 3,
    created_at: "2026-07-14T21:52:00.000Z",
    href: buildInternalDemoAssetHref("ica", "charles-drummond-v5"),
  },
  {
    id: "kevin-bowers-v2",
    project_id: "ica",
    folder_id: "ica-executive-interviews",
    title: "Kevin Bowers_v2",
    thumbnail_url: "/demo/control-room.jpg",
    file_type: "video",
    duration_seconds: 72,
    status: "in_review",
    version_count: 2,
    reviewer_count: 1,
    reviewer_done: 0,
    comment_count: 2,
    created_at: "2026-07-14T21:40:00.000Z",
    href: buildInternalDemoAssetHref("ica", "kevin-bowers-v2"),
  },
  {
    id: "ica-roadshow-final",
    project_id: "ica",
    folder_id: "ica-roadshow-master",
    title: "ICA_ROADSHOW_x_FINAL",
    thumbnail_url: "/demo/refinery-sunset.jpg",
    file_type: "video",
    duration_seconds: 60,
    status: "approved",
    version_count: 5,
    reviewer_count: 2,
    reviewer_done: 2,
    comment_count: 9,
    created_at: "2026-03-08T16:12:00.000Z",
    href: buildInternalDemoAssetHref("ica", "ica-roadshow-final"),
  },
  {
    id: "mclaren-podcast-v3",
    project_id: "schneider-epc",
    folder_id: "schneider-podcast",
    title: "Schneider + McLaren Podcast_v3",
    thumbnail_url: "/demo/crew-field-shoot.jpg",
    file_type: "video",
    duration_seconds: 1482,
    status: "needs_changes",
    version_count: 3,
    reviewer_count: 3,
    reviewer_done: 1,
    comment_count: 14,
    created_at: "2026-07-13T18:15:00.000Z",
    href: buildInternalDemoAssetHref("schneider-epc", "mclaren-podcast-v3"),
  },
  {
    id: "epc-recap-v6",
    project_id: "schneider-epc",
    folder_id: "schneider-roadshow",
    title: "SCHNEIDER_EPC_RECAP_v6",
    thumbnail_url: "/demo/control-room.jpg",
    file_type: "video",
    duration_seconds: 122,
    status: "approved",
    version_count: 6,
    reviewer_count: 3,
    reviewer_done: 3,
    comment_count: 11,
    created_at: "2026-07-11T20:10:00.000Z",
    href: buildInternalDemoAssetHref("schneider-epc", "epc-recap-v6"),
  },
  {
    id: "bp-rodeo-v2",
    project_id: "bp",
    folder_id: null,
    title: "BP Rodeo Recap_v2",
    thumbnail_url: "/demo/refinery-sunset.jpg",
    file_type: "video",
    duration_seconds: 94,
    status: "in_review",
    version_count: 2,
    reviewer_count: 4,
    reviewer_done: 2,
    comment_count: 5,
    created_at: "2026-07-12T14:20:00.000Z",
    href: buildInternalDemoAssetHref("bp", "bp-rodeo-v2"),
  },
  {
    id: "acs-brand-story-v1",
    project_id: "acs",
    folder_id: null,
    title: "ACS Brand Story_v1",
    thumbnail_url: "/demo/crew-field-shoot.jpg",
    file_type: "video",
    duration_seconds: 83,
    status: "draft",
    version_count: 1,
    reviewer_count: 0,
    reviewer_done: 0,
    comment_count: 0,
    created_at: "2026-07-14T19:08:00.000Z",
    href: buildInternalDemoAssetHref("acs", "acs-brand-story-v1"),
  },
];
